services:
  - type: web
    name: mini-ecommerce-api
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && node dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3000
